eureka:
  client:
    registerWithEureka: false
    serviceUrl:
defaultZone: http://localhost:8761/eureka/


# Spring properties
spring:
  application:
     name: hystrix-dashboard-service  # Service registers under this name
 
server:
  port: 4444   # HTTP (Tomcat) port
