# Spring properties
spring:
  application:
     name: hystrixser  # Service registers under this name
 
server:
  port: 4444   # HTTP (Tomcat) port

eureka:  
  client:
    serviceUrl:
defaultZone: http://localhost:8761/eureka/
