# Spring properties
spring:
  application:
     name: hystrix  # Service registers under this name
 
server:
  port: 4444   # HTTP (Tomcat) port
  
# Discovery Server Access
eureka:  
  client:
    serviceUrl:
defaultZone: http://localhost:8761/eureka/
