zuul:
  routes:
   MicroA-Config:
      path: /greeting/
      serviceId: MicroA-Config
      stripPrefix: false
   Microb-Config:
      path: /Saludo/
      serviceId: Microb-Config
      stripPrefix: false
   MicroA-Config:
      path: /greeting/
      serviceId: Microc-Config
      stripPrefix: false
   
   
      

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 
server:
  port: 5555   # HTTP (Tomcat) port
  
spring:
 application:
    name:  htc-ea-spring-zuul-services
