# HTTP Server
server:  
  port: 0   # HTTP port

# Discovery Server Access
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
      
# Access to the data base
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123456
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/ProductCostingV2
    username: postgres
values:
  cesc: 1.05
  iva: 1.13
  pemploye: 1.15
  pwholesale: 1.25
  pschool: 1.35
  psalesroom: 1.45
  
