zuul:
  routes:
   microa-config:
      path: /registercosting/**
      serviceId: MICROA-CONFIG
      stripPrefix: false
   Microb-Config:
      path: /Saludo/**
      serviceId: microb-config
      stripPrefix: false
   microc-Config:
      path: /comoestan/**
      serviceId: microc-service
      stripPrefix: false
   
   
      

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
server:
  port: 5555   # HTTP (Tomcat) port
  
spring:
 application:
    name:  htc-ea-spring-zuul-services
