server:  
  port: 0   # HTTP port

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:1111//eureka/
      
# Access to the data base
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123456
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/ProductCostingV2
    username: postgres
