zuul:
  routes:
   microa-config:
      path: /registercosting/**
      serviceId: MICROA-CONFIG
      stripPrefix: false
   Microb-Config:
      path: /consult/**
      serviceId: microb-config
      stripPrefix: false
   microc-Config:
      path: /ReadFile/**
      serviceId: microc-service
      stripPrefix: false
   
# Discovery Server Access
eureka:
  client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
 
server:
  port: 5555   # HTTP (Tomcat) port
  
spring:
 application:
    name:  micro-zuul
