zuul:
  routes:
    consult-greetings:
      path: /nombre de la ruta/**
      serviceId: htc-ea-spring-eurek-services
      stripPrefix: false
      

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 
server:
  port: 5555   # HTTP (Tomcat) port
  
spring:
 application:
    name:  htc-ea-spring-zuul-services
