# HTTP Server
server:  
  port: 0   # HTTP port

# Discovery Server Access
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# Access to the data base
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123456
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/ProductCostingV2
    username: postgres
values:
  Cesc: 1.05
  Iva: 1.13
