server:  
  port: ${PORT:8072}

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
# Access to the data base
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123456
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/ProductCostingV2
    username: postgres
    
  # values taxses
iva:  0.13
cesc: 0.05

# value validations
found: not fund
exit: exitoso
