# Spring properties
spring:
  application:
     name: turbine  # Service registers under this name
 
server:
  port: 4444   # HTTP (Tomcat) port
  
  turbine:
  aggregator:
    clusterConfig: MICRO-ZUUL
  appConfig: micro-zuul
  
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111//eureka/

  
